2025-10-04 13:45:48,583 INFO    MainThread:37152 [wandb_setup.py:_flush():81] Current SDK version is 0.22.1
2025-10-04 13:45:48,583 INFO    MainThread:37152 [wandb_setup.py:_flush():81] Configure stats pid to 37152
2025-10-04 13:45:48,583 INFO    MainThread:37152 [wandb_setup.py:_flush():81] Loading settings from /home/luca/.config/wandb/settings
2025-10-04 13:45:48,583 INFO    MainThread:37152 [wandb_setup.py:_flush():81] Loading settings from /home/luca/code/workspace/personal/Dream/wandb/settings
2025-10-04 13:45:48,583 INFO    MainThread:37152 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-10-04 13:45:48,584 INFO    MainThread:37152 [wandb_init.py:setup_run_log_directory():705] Logging user logs to /home/luca/code/workspace/personal/Dream/wandb/run-20251004_134548-hbzlb7ny/logs/debug.log
2025-10-04 13:45:48,584 INFO    MainThread:37152 [wandb_init.py:setup_run_log_directory():706] Logging internal logs to /home/luca/code/workspace/personal/Dream/wandb/run-20251004_134548-hbzlb7ny/logs/debug-internal.log
2025-10-04 13:45:48,584 INFO    MainThread:37152 [wandb_init.py:init():832] calling init triggers
2025-10-04 13:45:48,584 INFO    MainThread:37152 [wandb_init.py:init():837] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-10-04 13:45:48,584 INFO    MainThread:37152 [wandb_init.py:init():880] starting backend
2025-10-04 13:45:48,787 INFO    MainThread:37152 [wandb_init.py:init():883] sending inform_init request
2025-10-04 13:45:48,789 INFO    MainThread:37152 [wandb_init.py:init():891] backend started and connected
2025-10-04 13:45:48,790 INFO    MainThread:37152 [wandb_init.py:init():961] updated telemetry
2025-10-04 13:45:48,792 INFO    MainThread:37152 [wandb_init.py:init():985] communicating run to backend with 90.0 second timeout
2025-10-04 13:45:54,099 INFO    MainThread:37152 [wandb_init.py:init():1036] starting run threads in backend
2025-10-04 13:45:54,132 INFO    MainThread:37152 [wandb_run.py:_console_start():2506] atexit reg
2025-10-04 13:45:54,133 INFO    MainThread:37152 [wandb_run.py:_redirect():2354] redirect: wrap_raw
2025-10-04 13:45:54,133 INFO    MainThread:37152 [wandb_run.py:_redirect():2423] Wrapping output streams.
2025-10-04 13:45:54,133 INFO    MainThread:37152 [wandb_run.py:_redirect():2446] Redirects installed.
2025-10-04 13:45:54,134 INFO    MainThread:37152 [wandb_init.py:init():1076] run started, returning control to user process
2025-10-04 13:46:18,912 INFO    wandb-AsyncioManager-main:37152 [service_client.py:_forward_responses():80] Reached EOF.
2025-10-04 13:46:18,912 INFO    wandb-AsyncioManager-main:37152 [mailbox.py:close():137] Closing mailbox, abandoning 1 handles.
2025-10-04 13:46:19,296 ERROR   MainThread:37152 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2433, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 1595, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/interface/interface.py", line 802, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 37, in _publish_output_raw
    self._publish(rec)
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 43, in _publish
    self._asyncer.run(lambda: self._client.publish(request))
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/lib/asyncio_manager.py", line 136, in run
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/nix/store/gf7b5x6vh2g3bq054lm5pj7zqzfx7vjc-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/gf7b5x6vh2g3bq054lm5pj7zqzfx7vjc-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/lib/asyncio_manager.py", line 219, in _wrap
    return await fn()
           ^^^^^^^^^^
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/lib/service/service_client.py", line 38, in publish
    await self._send_server_request(request)
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/lib/service/service_client.py", line 64, in _send_server_request
    await self._writer.drain()
  File "/nix/store/gf7b5x6vh2g3bq054lm5pj7zqzfx7vjc-python3-3.11.13/lib/python3.11/asyncio/streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "/nix/store/gf7b5x6vh2g3bq054lm5pj7zqzfx7vjc-python3-3.11.13/lib/python3.11/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
2025-10-04 13:46:19,297 ERROR   MainThread:37152 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2433, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 1595, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/interface/interface.py", line 802, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 37, in _publish_output_raw
    self._publish(rec)
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 43, in _publish
    self._asyncer.run(lambda: self._client.publish(request))
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/lib/asyncio_manager.py", line 136, in run
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/nix/store/gf7b5x6vh2g3bq054lm5pj7zqzfx7vjc-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/gf7b5x6vh2g3bq054lm5pj7zqzfx7vjc-python3-3.11.13/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/lib/asyncio_manager.py", line 219, in _wrap
    return await fn()
           ^^^^^^^^^^
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/lib/service/service_client.py", line 38, in publish
    await self._send_server_request(request)
  File "/home/luca/code/workspace/personal/Dream/.venv/lib/python3.11/site-packages/wandb/sdk/lib/service/service_client.py", line 64, in _send_server_request
    await self._writer.drain()
  File "/nix/store/gf7b5x6vh2g3bq054lm5pj7zqzfx7vjc-python3-3.11.13/lib/python3.11/asyncio/streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "/nix/store/gf7b5x6vh2g3bq054lm5pj7zqzfx7vjc-python3-3.11.13/lib/python3.11/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
2025-10-04 13:46:20,221 INFO    MainThread:37152 [wandb_run.py:_finish():2272] finishing run lucamanolache/diff-verl/hbzlb7ny
